server:
  port: 3000
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  devtools:
    livereload:
      enabled: true
  application:
    name: serials
  datasource:
    url: jdbc:postgresql://localhost:5432/serialdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    web: DEBUG