server:
  port: 3000
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  devtools:
    livereload:
      enabled: true
  application:
    name: serials
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/serialdb
#    r2dbc:
#      repositories:
#        enabled: true
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/serialdb
#    username: postgres
#    password: root
#    pool:
#      enabled: true
logging:
  level:
    web: DEBUG